### ISSUE TITLE
Does not comply with MIT licensing

### ISSUE THREAD

**Issue by CodyJasonBennett** [whoisryosuke/r3f-next-starter#2]
This project is sourced from https://github.com/pmndrs/react-three-next, which is under the MIT license. You may dual-license, but the original license must be included unmodified in vendored works.

**Comment by whoisryosuke** [comment]
This is based on [create-r3f-app](https://github.com/utsuboco/create-r3f-app) as [clearly stated here](https://whoisryosuke.com/blog/2022/react-three-fiber-and-nextjs-starter-template/). 

The original author has been credited for the foundational work in the [README](https://github.com/whoisryosuke/r3f-next-starter#credits) and [package.json](https://github.com/whoisryosuke/r3f-next-starter/blob/main/package.json#L6). Their MIT license did not include references to [[react-three-next](https://github.com/pmndrs/react-three-next)](https://github.com/pmndrs/react-three-next).

Once this project deviated from the original repo, I assigned "ownership" to me, since most code is or will be mine. To dual-license would make it unclear in this case, since it's not a 3rd party library or portion of the app. But I still want to respect the author and their work, which is why I've credited them.

**Comment by CodyJasonBennett** [comment]
No, this project is indeed based on https://github.com/pmndrs/react-three-next as you can see since b8e598e0bf8bcb6373784f21f97a5564859caf83. The original files, folder structure, and even assets are visible. Furthermore, the date range and project name are included in the current license since 6c0d7ee563e38d894d2549dc021b0153e6eac6e0 and metadata in the previous commit, respectively.

I appreciate the effort to credit the original author of these works, but it does not do so in a way that respects its respective licensing. I've opened this issue to clarify the terms of the project's licensing and how it applies here.
